name: flutter_app
description: A new Flutter application.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  splashscreen: ^1.2.0
  shape_of_view: ^1.0.2
  flutter_svg: ^0.17.4
  carousel_slider: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/NunitoSans-SemiBold.ttf
  assets:
    - assets/

